# Site settings
title: Binarahandra
email: binarahandra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://binarahandra.com" # the base hostname & protocol for your site
twitter_username: binarahandra
github_username:  binar

# Build settings
markdown: kramdown
